//var APP_ROOT = 'http://localhost/quotes/';
var APP_ROOT = 'http://jaagar.org/quotes/';
var SERVICE_ROOT = 'v1.2/';

var configs = {};
configs['REGISTER_VALIDATION_NAME'] = 'Name should be atleast 5 characters long.';
// App messages
configs['ACCOUNT_NOT_ACTIVE'] = 'The account is still not active, please check your email to activate.';
configs['LOGIN_FAIL'] = 'Login Failed, please try again.';
configs['RESET_EMAIL_SENT'] = 'The email is sent to the given email ID, provided it was found in our database.';
configs['REGISTER_SUCCESS'] = 'Registered Successfully. Please check your email to activate the account.';
configs['REGISTER_FAILURE'] = 'We are facing a technical issue in creating your account, please try again after some time.';
configs['USER_ALREADY_VERIFIED'] = 'User is already verified please login.';
configs['USER_VERIFIED'] = 'Verification complete please login.';
configs['USER_VERIFICATION_ERR'] = 'There was an error in email verification.';
configs['PASSWORD_RESET'] = 'Please enter your new password to reset.';
configs['PASSWORD_RESET_USED'] = 'The reset link is either used or a new link has been requested.';
configs['PASSWORD_CHANGED'] = 'The password has been changed please login with your new credentials.';
configs['PASSWORD_CHANGE_FAIL'] = 'The password change link seems to have expired.';
//validation messages
configs['REGISTER_VALIDATION_NAME'] = 'Name should be atleast 4 character long and without special characters.';
configs['REGISTER_VALIDATION_EMAIL'] = 'Invalid Email Id.';
configs['REGISTER_VALIDATION_PASSWORD'] = 'Use strong password that contains at least 6 characters, a special character, a number and a capital letter.';
configs['REGISTER_VALIDATION_CAPTCHA'] = 'Your entered captcha was wrong please re-enter.';
configs['REGISTER_LOGIN'] = 'Login to the application, if email verification is complete.';
configs['EMAIL_VERIFY_SENT'] = 'Verification email is sent to your email Id';
configs['EMAIL_VERIFY_SENT_FAIL'] = 'There was an error in sending out verification email, please try after some time';
configs['CTG_NAME_LENGTH_ERR'] = 'Category name should be atleast 5 character long.';
configs['CTG_DESC_LENGTH_ERR'] = 'Category description should be atleast 30 character long.';
configs['INVALID_EMAIL_ERR'] = 'Please Enter a valid email Id.';
configs['LOGIN_PSWD_REQUIRED'] = 'Password is required.';
configs['LOGOUT_MESSAGE'] = 'You are successfully logged out of the application.';
configs['QUOTE_LENGTH_ERR'] = 'Quote should be atleast atleast 30 character long.';
configs['PASSWORD_NO_MATCH'] = 'Password do not match.';
configs['DATA_NOT_FOUND'] = 'Error in fetching categories';
configs['DELETE_ERROR'] = 'Requested resource could not be deleted.';
configs['UPDATE_ERROR'] = 'Requested resource could not be updated.';
configs['CREATE_ERROR'] = 'Requested resource could not be created.';
configs['SERVICE_ERROR'] = 'A service error has occurred please try after some time.'